name: Dcoker-ci-pipeline
on: push
jobs:
  dockerci-job:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v6
        
      - name: Build image
        run: docker build -t ${{ vars.DOCKER_USERNAME}}/helloworld-demo-python:v1 .
        
      - name: Verify image
        run: docker images
        
      - name: Create container
        run: docker run --name python-app -idt -p 8080:8080 ${{ vars.DOCKER_USERNAME}}/helloworld-demo-python:v1

      - name: Verify the container
        run: docker ps
        
      - name: Curl output
        run: curl http://localhost:8080
        
      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ vars.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_TOEKN}}
          
      - name: Push image
        run: docker push ${{ vars.DOCKER_USERNAME}}/helloworld-demo-python:v1 

      - name: Container cleanup
        run: docker rm python-app 
      
 
